manifestVersion: subsquid.io/v0.1
name: gs-main-acala
version: 1
description: |-
  Giant Squid Explorer for Acala chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: acala
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_ACALA_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    cmd:
      - sqd
      - serve:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 30G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
