manifestVersion: subsquid.io/v0.1
name: gs-main-amplitude
version: 1
description: |-
  Giant Squid Main for Amplitude chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: amplitude
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_AMPLITUDE_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: amplitude
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 30G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
