manifestVersion: subsquid.io/v0.1
name: gs-main-astar
version: 1
description: |-
  Giant Squid Explorer for Astar chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: astar
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_ASTAR_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: astar
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 40G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
