manifestVersion: subsquid.io/v0.1
name: gs-main-basilisk
version: 1
description: |-
  Giant Squid Main for Basilisk
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: basilisk
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_BASILISK_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: basilisk
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 30G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
