manifestVersion: subsquid.io/v0.1
name: gs-main-bifrostpolkadot
version: 1
description: |-
  Giant Squid Main for Bifrost Polkadot Chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: bifrost_polkadot
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_BIFROST_POLKADOT_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: bifrost_polkadot
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 30G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
