manifestVersion: subsquid.io/v0.1
name: gs-main-centrifuge
version: 1
description: |-
  Giant Squid Main for Centrifuge Chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: centrifuge
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_CENTRIFUGE_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: centrifuge
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 30G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
