manifestVersion: subsquid.io/v0.1
name: gs-main-hydradx
version: 1
description: |-
  Giant Squid Explorer for HydraDX chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: hydradx
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_HYDRADX_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: hydradx
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 30G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
