manifestVersion: subsquid.io/v0.1
name: gs-main-integritee
version: 1
description: |-
  Giant Squid Main for Integritee
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: integritee
    CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_INTEGRITEE_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: integritee
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 30G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
