manifestVersion: subsquid.io/v0.1
name: gs-main-kusama
version: 1
description: |-
  Giant Squid Explorer for Kusama chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: kusama
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_KUSAMA_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: kusama
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 70G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
