manifestVersion: subsquid.io/v0.1
name: gs-main-kusama
version: 100
description: |-
  Giant Squid Explorer for Kusama chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      RPC_WSS: wss://kusama.api.onfinality.io/public-ws
    cmd: ["node", "lib/kusama/main"]
  api:
    cmd:
      [
        "npx",
        "squid-graphql-server",
        "--dumb-cache",
        "in-memory",
        "--dumb-cache-ttl",
        "1000",
        "--dumb-cache-size",
        "100",
        "--dumb-cache-max-age",
        "1000",
      ]
scale:
  dedicated: true
  processor:
    profile: medium
