manifestVersion: subsquid.io/v0.1
name: gs-main-litentry
version: 1
description: |-
  Giant Squid Main for Litentry Network
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: litentry
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_LITENTRY_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: litentry
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 30G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
