manifestVersion: subsquid.io/v0.1
name: gs-main-moonriver
version: 1
description: |-
  Giant Squid Explorer for Moonriver chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: moonriver
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_MOONRIVER_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: moonriver
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 180G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
