manifestVersion: subsquid.io/v0.1
name: gs-main-moonbeam
version: 1
description: |-
  Giant Squid Explorer for Moonbeam chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: moonbeam
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_MOONBEAM_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: moonbeam
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 240G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
