manifestVersion: subsquid.io/v0.1
name: gs-main-pendulum
version: 1
description: |-
  Giant Squid Main for Pendulum chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: pendulum
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_PENDULUM_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: pendulum
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 70G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
