manifestVersion: subsquid.io/v0.1
name: gs-main-picasso
version: 1
description: |-
  Giant Squid Main for Picasso
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: picasso
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_PICASSO_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: picasso
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 30G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
