manifestVersion: subsquid.io/v0.1
name: gs-main-polkadot
version: 1
description: |-
  Giant Squid Explorer for Polkadot chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: polkadot
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_POLKADOT_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: polkadot
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 140G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
