manifestVersion: subsquid.io/v0.1
name: gs-main-shiden
version: 1
description: |-
  Giant Squid Explorer for Shiden chain
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: shiden
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_SHIDEN_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: shiden
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 30G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
