manifestVersion: subsquid.io/v0.1
name: gs-main-ternoa
version: 1
description: |-
  Giant Squid Main for Ternoa
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: ternoa
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_TERNOA_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    cmd:
      - sqd
      - serve:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 30G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
