manifestVersion: subsquid.io/v0.1
name: gs-main-turing
version: 1
description: |-
  Giant Squid Main for Turing Network
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: turing
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_TURING_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: turing
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 90G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
