manifestVersion: subsquid.io/v0.1
name: gs-main-zeitgeist
version: 1
description: |-
  Giant Squid Main for Zeitgeist
build:
deploy:
  addons:
    postgres:
  processor:
    env:
      CHAIN: zeitgeist
      CHAIN_RPC_ENDPOINT: ${{ secrets.RPC_ZEITGEIST_HTTP }}
    cmd:
      - sqd
      - process:prod
  api:
    env:
      CHAIN: zeitgeist
    cmd:
      - sqd
      - api:prod
scale:
  dedicated: true
  addons:
    postgres:
      storage: 90G
      profile: medium
  api:
    profile: medium
  processor:
    profile: medium
