export * as staking from './staking/calls'
export * as identity from './identity/calls'
export * as crowdloan from './crowdloan/calls'
export * as nominationPools from './nomination-pools/calls'
export * as convictionVoting from './conviction-voting/calls'
