export * as balances from './balances/events'
export * as staking from './staking/events'
export * as identity from './identity/events'
export * as registrar from './registrar/events'
export * as crowdloan from './crowdloan/events'
export * as xcmPallet from './xcm-pallet/events'
