name: Build & Generate project files

on:
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 20]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Squid CLI
        run: |
          npm i -g @subsquid/cli@latest
          sqd --version

      - name: Install Dependencies
        run: npm ci

      - name: Build the Indexer
        run: sqd build

  generate:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [16, 20]

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}

      - name: Install Squid CLI
        run: |
          npm i -g @subsquid/cli@latest
          sqd --version

      - name: Install Dependencies
        run: npm ci

      - name: Generate TypeORM entities from the `schema.graphql` file
        run: sqd codegen

      - name: Generate Substrate metadata types from `typegen/<chain>.json`
        run: sqd typegen
